### ISSUE TITLE
Laravel Exception View Breaking

### ISSUE THREAD

**Issue by truehybridx** [spatie/laravel-csp#49]
This might not be something that can be addressed in this extension or maybe I missed something.

With the Basic CSP policy enabled the Laravel debugger page stops functioning due to inline styles and such. Is it possible for those that to be detected so it functions properly when in debug mode? I am not sure allowing inline styles and scripts in the CSP app wide for this to work would be a good approach.

Did I miss something?

Attached are two images, one with the debug view showing and the other with it being disabled because of inline script/styles.

![1](https://user-images.githubusercontent.com/39617/50388217-70190780-06d5-11e9-957b-376e3960f59d.PNG)
![2](https://user-images.githubusercontent.com/39617/50388218-70b19e00-06d5-11e9-833d-0910572d8da0.PNG)

**Comment by Gummibeer** [comment]
My first idea would be something in the middleware https://github.com/spatie/laravel-csp/blob/master/src/AddCspHeaders.php to don't apply if it's an exception.
I haven't tested it - but you are 100% right that your app shouldn't allow something you only need for development.

Another idea, without adjustments in the package, would be to use an env var to define the policy class and have a normal one and a development one.

**Comment by freekmurze** [comment]
Closing this as I think we don't need to fix this in this package

> Another idea, without adjustments in the package, would be to use an env var to define the policy class and have a normal one and a development one.

Seems like a good suggestion!

**Comment by nrdmn** [comment]
> Another idea, without adjustments in the package, would be to use an env var to define the policy class and have a normal one and a development one.
I think an application must not change its behavior in a way that may break it when configured to run in production mode. Developers will forget to switch and test whether it still works with CSP enabled.

**Comment by truehybridx** [comment]
Alright, I will go with the idea of changing up the policy depending on the environment. Might be better that way but creates the added concern about accidentally leaving the weaker CSP enabled or not correctly testing the stronger CSP since it wasn't in use during development. I think it is manageable though.

**Comment by Gummibeer** [comment]
@truehybridx let's say that we allow inline styles if a package is installed or something like this. This would be even more bad because this policy would be added by "magic" and you would wonder why something works during development but not on production.
And you could also test the production setup on your local machine. Add a `.env.prod` with your `CSP_POLICY`, change your `APP_ENV` to `prod` and run `composer update --no-dev`. If you have done your switch right this would enable the production policy and you can test it on your local machine.

**Comment by Gummibeer** [comment]
@mbehnke like I said - I don't see any way to solve it inside of this package. And I also can't agree with
> I think an application must not change its behavior in a way that may break it when configured to run in production mode.
There are a lot of ENV variables that change the behavior of the app and could also lead to bugs if not set correctly. That is what ENV variables are made for and why they should be set with responsibility.

And extending the real policy by a local/development one that allows inline isn't this bad. The other question could be: why does the other package not load real assets instead of inline ones?
Also I would develop with the normal policy until I get an error page, otherwise I could develop with inline styles and they would work.

So giving the developer the choice and an easy way to solve it (it is there) is nothing bad.

**Comment by Gummibeer** [comment]
Another solution I see is to use the app container. We use the `PolicyFactory::create()` method to get an instance of the used policy. This method uses `app($policyClassName)` to get an instance of it.
So if you bind the policy class in a service provider as singleton it will load the bound instance. This instance could be manipulated in the `ExceptionHandler::render()` method (the `Policy::addDirective()` method is public).

```php
// AppServiceProvider
$this->app->singleton(AppPolicy::class, new AppPolicy());

// ExceptionHandler::render()
app(AppPolicy::class)->addDirective(Directive::STYLE, Keyword::UNSAFE_INLINE)
```

I haven't test it but it should lead to a policy which allows unsafe inline styles if the response is returned by the `ExceptionHandler::render()` method.

**Comment by nrdmn** [comment]
`singleton` takes a closure as its second parameter. I've added this to `render` in app/Exceptions/Handler.php:
```php
$this->container->singleton(AppPolicy::class, function ($app) {
    return new AppPolicy();
});
app(AppPolicy::class)->addDirective(Directive::SCRIPT, Keyword::UNSAFE_INLINE);
app(AppPolicy::class)->addDirective(Directive::STYLE, Keyword::UNSAFE_INLINE);
```
Note that `unsafe-inline` only works if you're not also sending a nonce or a `strict-dynamic` directive, so you can only use inline scripts/styles elsewhere in your app if you specify their hashes in the CSP header.

**Comment by Gummibeer** [comment]
@nrdmn I would say that you can add a new chapter to the README after `Reporting CSP errors` with your code as a suggestion for others coming across this problem.
And thanks for your fix :) - wasn't sure which type is required/allowed as the second argument.
It could be worth a note that this will also work for every other situation to change the policy on runtime, in this case the singleton registration should be done in a service provider instead of the exception handler.
