### ISSUE TITLE
Redirect after POST blocked by CSP

### ISSUE THREAD

**Issue by fred-cardoso** [spatie/laravel-csp#55]
Hi!

I am facing a issue with the implementation of CSP.

So, after POSTing data to a URL, for some reason Laravel makes a response to http instead of https, making the browser block the redirect (on a login for example) and canceling the HTTP process which makes the page to stay on the form.

For example:

```
RedirectResponse {#281 ▼
  #request: Request {#43 ▶}
  #session: EncryptedStore {#225 ▶}
  #targetUrl: "https://alpha.*********.**/admin"
  +headers: ResponseHeaderBag {#278 ▶}
  #content: """
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8" />
            <meta http-equiv="refresh" content="0;url=https://alpha.*********.**/admin" />
    
            <title>Redirecting to https://alpha.*********.**/admin</title>
        </head>
        <body>
            Redirecting to <a href="https://alpha.*********.**/admin">https://alpha.*********.**/admin</a>.
        </body>
    </html>
    """
  #version: "1.0"
  #statusCode: 302
  #statusText: "Found"
  #charset: null
  +original: null
  +exception: null
}
```

The above log is dumped right before the return for the browser.

So, although this seems fine, the browser log shows this:

`Refused to send form data to 'http://alpha.*********.**/' because it violates the following Content Security Policy directive: "form-action 'self' *.*********.**".`

Disabling the CSP for Form actions solves the issue (temporarily).

Any idea on where might be the issue?

I tried tracing the responses, but they seem OK.

Thanks!

**Comment by Gummibeer** [comment]
Could you open your network tab in your browser and check what's going on?

So where your post sends the data, what's the response and so on.
Everything until the CSP blocks a request.

Have you set your app URL in the config with https?

**Comment by fred-cardoso** [comment]
Hi!

I am disregarding the first page loading process. So after that, and after I push the submit, I only get this:

![image](https://user-images.githubusercontent.com/32043667/54121427-4d53e080-43f2-11e9-9efc-e6fc1e9e05fd.png)


Yes, the app URL is with https, and is automatically enforced by CloudFlare as well.

Thanks!

**Comment by Gummibeer** [comment]
Could you add the domain & schema or better the whole request page from the network tab?

To your question: I can nearly guarantee you that it's not this package that blocks your request. CSP is a standard implemented in the browser. This package only generates the needed header that is interpreted by the browser. The request is blocked by the browser not the server or this package.

So at all this should be related to a misconfiguration of your CSP policy, url generator or your form request.
The blocked url (schema/domain) is generated somewhere - the task to solve it now is to find out which exact request is blocked (the POST itself or the GET opened by the redirect) and why.

1. find out which Request is blocked - so far I see it's the GET request following the POST and initiated by the redirect response of the POST.
2. why is it blocked - mismatching schema (http vs https), mismatching domain (subdomain vs domain, different TLD)
3. is the generated url blocked of a valid reason (if you would validate the url following your CSP would it be also invalid) or is it blocked because of something like a caching problem
4. if it's valid blocked - find out where the invalid url comes from and try to fix it

As a following hint: read what CSP is and does https://content-security-policy.com - the header tells the browser which requests are allowed and which not. If you start a blocked request it isn't even send because the browser kills it immediately. That's why http to https redirects in cloudflare, nginx or wherever are useless because to make these technics work the browser should send the request. This would be against everything what CSP is about because the request would be send out, could contain data which are saved by an unallowed person, this is done even if the browser says: ok, this request wasn't allowed because it wasn'T redirected to a whitelisted domain so I don't show it. That's why redirects aren't important for CSP - CSP only cares about what's in your request itself and if this is valid.

**Comment by fred-cardoso** [comment]
How can I show the whole request page? I don't know what you mean. Sorry.

I think you are right. Somewhere, somehow, the laravel redirect seems to be generated to http instead of https.

I am sure that is the GET request the one being blocked because the POST actions are preformed (the login is done, only the redirect is not working as supposed).

It is blocked by a valid reason. I disabled CloudFlare caching and even tried on an anonymous window of Chrome.

I have no idea where it comes from (the invalid URL) because like I said on the first post, when I do a route with just a redirect response after a POST, it gets blocked. And all I am doing is something like:

`    Route::get('/', function () {
        return redirect()->back();
    });`

This is pseudocode. But I think it gives you the point.

So, do you have any idea on where I can check where is the invalid response being generated? Because when a put the redirect() into a variable and dump it, the result is the first result shown on first post. The redirect is, indeed https.

Thanks for your time.

**Comment by Gummibeer** [comment]
You can click on every request listed in the network tab to see all details (request, headers, data, response and so on). There you will see all information you need to debug it.

Another idea to debug the CSP would be to set it `report_only`. Set it to `csp.report_only_policy` and set `csp.policy` to `null` https://github.com/spatie/laravel-csp/blob/master/config/csp.php
You would also have to set the `csp.report_uri` https://report-uri.com otherwise you will only see it in the browser developer console.

Without the full trace of what tries to request what it will be very hard to debug. That's why I try to give you hints how to debug because I would need too much information to do it for you.

I don't know what you do in your login but could it be that you use oAuth? If so I have found something that could be related to your issue: https://github.com/w3c/webappsec-csp/issues/8
If not it could be that you will find useful information anyway.

In general I can tell you that `->addDirective(Directive::FORM_ACTION, Keyword::SELF)` works good, I have it in my own application and also do `return redirect()->back();` in my post methods.
So the only reason why it's blocked is that you open something else than `self`.

**Comment by fred-cardoso** [comment]
Just to let you know that I will check this ASAP. Thanks.
