### ISSUE TITLE
Error with Permissions-Policy header

### ISSUE THREAD

**Issue by Referion** [spatie/laravel-csp#82]
Hello. 

I've read here [https://github.com/w3c/webappsec-permissions-policy/blob/main/permissions-policy-explainer.md#appendix-big-changes-since-this-was-called-feature-policy](url) that Permissions Policy header syntax has recently changed. I don't know if that is related but I'm getting this error in Chrome console: 

`Error with Permissions-Policy header: Parse of permissions policy failed because of errors reported by structured header parser.`

And the following is an example of permissions-policy header: 

`geolocation 'self' 'none';fullscreen 'self';accelerometer 'none';ambient-light-sensor 'none';autoplay 'none';camera 'none';document-domain 'self';encrypted-media 'self';execution-while-not-rendered 'self';execution-while-out-of-viewport 'self';gyroscope 'none';magnetometer 'none';microphone 'none';midi 'none';payment 'none';picture-in-picture 'none';speaker 'none';sync-xhr 'self';usb 'none';vr 'none';wake-lock 'none'`

I'm using Laravel 8.61.0 with PHP 7.4.21.

Anybody else is getting this error? Is this something to be fixed in this laravel-csp library? 

Thanks in advance.

**Comment by joostdebruijn** [comment]
This library is for creating Content Security Policies and not for Permission Policies, so this error is not related to this package.

**Comment by customeer** [comment]
I know, and the error I reported was caused by the Content Security Policies headers generated by this laravel-csp package, although the error is displayed in the browser console as "Error with Permission-Policy header". 

I mean, the browser is still referring "Content Security Policies" as "Permission Policies". But besided that, the error comes from the headers created by this package.

**Comment by joostdebruijn** [comment]
I'm very sure those headers are not generated by this package, because directives like `geolocation` and `fullscreen`, etc. in the bug report are not part of the Content Security Policy header spec and are also not part of [the directives offered in this package](https://github.com/spatie/laravel-csp/blob/main/src/Directive.php).

The Content-Security-Policy header and Permission-Policy (former Feature-Policy header) are different specs and serve a different purpose, so I don't think the browser is mixing things up. I'm very sure the header which is causing the browser error is not generated by this package, but is generated elsewhere.
